# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(db_column='displayurl', max_length=1000)),
                ('price', models.IntegerField(db_column='price__c', max_length=18)),
                ('currency', models.CharField(db_column='currency__c', max_length=5)),
                ('description', models.CharField(db_column='description__c', max_length=255)),
            ],
            options={
                'db_table': '"salesforce"."product2"',
                'managed': False,
            },
        ),
    ]
