# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column=b'cst_name__c', max_length=32)),
                ('surname', models.CharField(db_column=b'cst_surname__c', max_length=32)),
                ('street', models.CharField(db_column=b'cst_street__c', max_length=32)),
                ('postalcode', models.CharField(db_column=b'cst_postal_code__c', max_length=32)),
                ('city', models.CharField(db_column=b'cst_city__c', max_length=32)),
                ('email', models.CharField(db_column=b'cst_email__c', max_length=32)),
            ],
            options={
                'db_table': '"salesforce"."order__c"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column=b'name', max_length=255)),
                ('url', models.CharField(db_column=b'displayurl', max_length=1000)),
                ('price', models.DecimalField(db_column=b'price__c', decimal_places=2, max_digits=18)),
                ('currency', models.CharField(db_column=b'currency__c', max_length=5)),
                ('description', models.CharField(db_column=b'description__c', max_length=255)),
                ('sfid', models.CharField(db_column=b'sfid', max_length=18)),
            ],
            options={
                'db_table': '"salesforce"."product2"',
                'managed': False,
            },
        ),
    ]
